import { andhrapradesh, arunachalpradesh, assam, bihar, chhattisgarh, delhi, goa, nagaland, odisha, punjab, rajasthan, sikkim, tamilnadu, tripura, gujrat, telangana, haryana, uttarpradesh, himachalpradesh, uttarakhand, jharkhand, westbengal, karnataka, andamanandnicobar, kerala, chandigarh, maharashtra, dadraandnagarhaveli, madhyapradesh, damananddiu, manipur, jammuandkashmir, meghalaya, lakshadweep, mizoram, puducherry } from "@/assets"
const placeholderImg = '/placeholder.svg'


const statesData = [
    {
        id: "andhra-pradesh",
        name: "Andhra Pradesh",
        cardImage: andhrapradesh,
        gallery: [andhrapradesh],
        mapIcon: placeholderImg,
        type: "state",
        keyIndustries: ["Agriculture", "IT", "Manufacturing"],
        investmentOpportunities: "Strong opportunities in agriculture, IT parks, ports and renewable energy",
        economicAchievements:
            "Andhra Pradesh has seen significant economic growth with a focus on agriculture, IT, and manufacturing sectors.",
        infrastructureHighlights: "Development of Amaravati as the new capital, expansion of ports and airports.",
        demographics: "Diverse population with Telugu as the primary language.",
        policies: "Focus on promoting industries through policies like 'Sunrise Andhra Pradesh' and 'Ease of Doing Business.'",
    },
    {
        id: "nagaland",
        name: "Nagaland",
        cardImage: nagaland,
        gallery: [nagaland],
        mapIcon: placeholderImg,
        type: "state",
        keyIndustries: ["Agriculture", "Tourism", "Handicrafts"],
        investmentOpportunities: "Tourism and handicrafts with scope for niche agri-products",
        economicAchievements: "Predominantly agrarian economy with potential for growth in tourism and handicrafts.",
        infrastructureHighlights: "Improving road networks and connectivity in a hilly terrain.",
        demographics: "Predominantly Naga tribal population with diverse languages.",
        policies: "Emphasis on preserving tribal heritage and promoting agriculture.",
    },
    {
        id: "arunachal-pradesh",
        name: "Arunachal Pradesh",
        cardImage: arunachalpradesh,
        gallery: [arunachalpradesh],
        mapIcon: placeholderImg,
        type: "state",
        keyIndustries: ["Hydropower", "Tourism"],
        investmentOpportunities: "Hydropower and eco-tourism",
        economicAchievements: "Developing its economy with an emphasis on hydropower projects and tourism.",
        infrastructureHighlights: "Expanding road connectivity in a geographically challenging region.",
        demographics: "Diverse tribal population.",
        policies: "Focus on sustainable development and preserving indigenous culture.",
    },
    {
        id: "odisha",
        name: "Odisha",
        cardImage: odisha,
        gallery: [odisha],
        mapIcon: placeholderImg,
        type: "state",
        keyIndustries: ["Mining", "Agriculture", "Manufacturing"],
        investmentOpportunities: "Ports, mining, and downstream industries",
        economicAchievements: "Steady growth with a focus on mining, agriculture, and manufacturing.",
        infrastructureHighlights: "Developing ports, highways, and power infrastructure.",
        demographics: "Diverse population with Odia as the primary language.",
        policies: "Focus on industrialization, mining, and social development.",
    },
    {
        id: "assam",
        name: "Assam",
        type: "state",
        cardImage: assam,
        gallery: [assam],
        keyIndustries: ["Tea", "Oil", "Agro-Processing"],
        investmentOpportunities: "Logistics and agro-processing",
        economicAchievements: "Economic growth driven by tea, oil, and agriculture.",
        infrastructureHighlights: "Expanding road and rail networks, improving connectivity.",
        demographics: "Diverse ethnic groups and languages.",
        policies: "Various policies to promote tea, tourism, and skill development.",
    },
    {
        id: "punjab",
        name: "Punjab",
        type: "state",
        cardImage: punjab,
        gallery: [punjab],
        keyIndustries: ["Agriculture", "Food Processing"],
        investmentOpportunities: "Agri-processing and agro-exports",
        economicAchievements: "Strong agriculture-based economy, with a growing services sector.",
        infrastructureHighlights: "Modern transportation and irrigation facilities.",
        demographics: "Predominantly Punjabi-speaking population.",
        policies: "Focus on agriculture, education, and skill development.",
    },
    {
        id: "bihar",
        name: "Bihar",
        type: "state",
        cardImage: bihar,
        gallery: [bihar],
        keyIndustries: ["Agriculture", "Small-scale Industries"],
        investmentOpportunities: "Food processing and skill development",
        economicAchievements: "Gradual economic growth with an emphasis on agriculture and small-scale industries.",
        infrastructureHighlights: "Improvement in road and electricity infrastructure.",
        demographics: "High population density with a predominantly Hindi-speaking population.",
        policies: "Initiatives to promote industries and skill development.",
    },
    {
        id: "rajasthan",
        name: "Rajasthan",
        type: "state",
        cardImage: rajasthan,
        gallery: [rajasthan],
        keyIndustries: ["Tourism", "Mining", "Agriculture"],
        investmentOpportunities: "Tourism infrastructure and mining value-chains",

        economicAchievements: "Diverse economy with agriculture, tourism, and mining sectors.",
        infrastructureHighlights: "Developing tourism infrastructure, transportation, and irrigation projects.",
        demographics: "Predominantly Rajasthani-speaking population.",
        policies: "Emphasis on tourism promotion and water resource management.",
    },
    {
        id: "chhattisgarh",
        name: "Chhattisgarh",
        type: "state",
        cardImage: chhattisgarh,
        gallery: [chhattisgarh],
        keyIndustries: ["Mining", "Steel", "Power"],
        investmentOpportunities: "Mining and downstream manufacturing",

        economicAchievements: "Rapid industrial growth, especially in the mining and steel sectors.",
        infrastructureHighlights: "Development of industrial and transport infrastructure.",
        demographics: "Diverse population with a focus on tribal communities.",
        policies: "Policies to promote industrial growth and welfare of tribal populations.",
    },
    {
        id: "sikkim",
        name: "Sikkim",
        type: "state",
        cardImage: sikkim,
        gallery: [sikkim],
        keyIndustries: ["Tourism", "Organic Agriculture"],
        investmentOpportunities: "Eco-tourism and organic farming",

        economicAchievements: "Developing a sustainable economy with a focus on tourism and organic agriculture.",
        infrastructureHighlights: "Improving road connectivity in mountainous terrain.",
        demographics: "Diverse population with Nepali as the primary language.",
        policies: "Focus on organic farming, tourism, and environmental conservation.",
    },
    {
        id: "delhi",
        name: "Delhi",
        type: "ut",
        cardImage: delhi,
        gallery: [delhi],
        keyIndustries: ["Services", "Trade"],
        investmentOpportunities: "Services, education, and healthcare",

        economicAchievements: "Strong economy driven by the service sector and trade.",
        infrastructureHighlights: "Modern transportation, educational institutions, and healthcare facilities.",
        demographics: "Diverse population, including people from all over India.",
        policies: "Focus on improving public services, education, and healthcare.",
    },
    {
        id: "tamil-nadu",
        name: "Tamil Nadu",
        type: "state",
        cardImage: tamilnadu,
        gallery: [tamilnadu],
        keyIndustries: ["Manufacturing", "Services", "Automotive"],
        investmentOpportunities: "Manufacturing and exports",

        economicAchievements: "Robust manufacturing and services sector with strong infrastructure.",
        infrastructureHighlights: "Well-developed industrial hubs, ports, and educational institutions.",
        demographics: "Diverse population with Tamil as the primary language.",
        policies: "Pro-business policies, focus on industry, and education.",
    },
    {
        id: "goa",
        name: "Goa",
        type: "state",
        cardImage: goa,
        gallery: [goa],
        keyIndustries: ["Tourism", "Mining"],
        investmentOpportunities: "Tourism and hospitality",

        economicAchievements: "Tourism and mining contribute significantly to the economy.",
        infrastructureHighlights: "Modernized tourism infrastructure and transportation.",
        demographics: "Diverse population with Konkani as the primary language.",
        policies: "Emphasis on sustainable tourism and environmental conservation.",
    },
    {
        id: "tripura",
        name: "Tripura",
        type: "state",
        cardImage: tripura,
        gallery: [tripura],
        keyIndustries: ["Agriculture", "Tourism"],
        investmentOpportunities: "Tourism and agri-value chains",

        economicAchievements: "Economic growth with an emphasis on agriculture and tourism.",
        infrastructureHighlights: "Developing road and rail connectivity in a hilly region.",
        demographics: "Diverse population with Bengali and Kokborok as prominent languages.",
        policies: "Emphasis on promoting tourism and agriculture.",
    },
    {
        id: "gujarat",
        name: "Gujarat",
        type: "state",
        cardImage: gujrat,
        gallery: [gujrat],
        keyIndustries: ["Manufacturing", "Petrochemicals", "Ports"],
        investmentOpportunities: "Manufacturing, petrochemicals and port-led growth",

        economicAchievements: "Vibrant economy with a focus on manufacturing, petrochemicals, and ports.",
        infrastructureHighlights: "World-class industrial and port facilities.",
        demographics: "Diverse population with a strong industrial and business culture.",
        policies: "Pro-business policies, such as 'Make in Gujarat' and 'Vibrant Gujarat.'",
    },
    {
        id: "telangana",
        name: "Telangana",
        type: "state",
        cardImage: telangana,
        gallery: [telangana],
        keyIndustries: ["IT", "Agriculture", "Manufacturing"],
        investmentOpportunities: "IT parks and agro-processing",

        economicAchievements: "Rapid economic growth, driven by IT, agriculture, and manufacturing sectors.",
        infrastructureHighlights: "Well-developed IT parks, transportation, and educational institutions.",
        demographics: "Diverse population with Telugu as the primary language.",
        policies: "Pro-business policies, focus on IT, and skill development.",
    },
    {
        id: "haryana",
        name: "Haryana",
        type: "state",
        cardImage: haryana,
        gallery: [haryana],
        keyIndustries: ["Automotive", "Manufacturing"],
        investmentOpportunities: "Automotive and manufacturing clusters",
        majorCities: ["Gurugram", "Faridabad"],
        economicAchievements: "Rapid industrial growth with a focus on agriculture and manufacturing.",
        infrastructureHighlights: "Modern infrastructure and connectivity.",
        demographics: "Diverse population with a focus on agriculture and industry.",
        policies: "Pro-industry and investment-friendly policies.",
    },
    {
        id: "uttar-pradesh",
        name: "Uttar Pradesh",
        type: "state",
        cardImage: uttarpradesh,
        gallery: [uttarpradesh],
        keyIndustries: ["Agriculture", "Industry", "Services"],
        investmentOpportunities: "Industrial corridors and agro-processing",
        majorCities: ["Lucknow", "Kanpur", "Noida"],
        economicAchievements: "Mixed economy with agriculture, industry, and services sectors.",
        infrastructureHighlights: "Expanding transportation networks and industrial areas.",
        demographics: "Highly populous with Hindi as the primary language.",
        policies: "Initiatives to promote industrial growth and social welfare.",
    },
    {
        id: "himachal-pradesh",
        name: "Himachal Pradesh",
        type: "state",
        cardImage: himachalpradesh,
        gallery: [himachalpradesh],
        keyIndustries: ["Tourism", "Agriculture"],
        investmentOpportunities: "Eco-tourism and horticulture",
        majorCities: ["Shimla", "Dharamshala"],
        economicAchievements: "Steady growth in agriculture and tourism sectors.",
        infrastructureHighlights: "Developing road networks in the hilly terrain, improving healthcare and education.",
        demographics: "Diverse population with a mix of languages.",
        policies: "Emphasis on sustainable development, eco-tourism, and agricultural growth.",
    },
    {
        id: "uttarakhand",
        name: "Uttarakhand",
        type: "state",
        cardImage: uttarakhand,
        gallery: [uttarakhand],
        keyIndustries: ["Tourism", "Agriculture"],
        investmentOpportunities: "Tourism and small-scale industries",
        majorCities: ["Dehradun", "Nainital"],
        economicAchievements: "Developing its economy with a focus on tourism, agriculture, and small-scale industries.",
        infrastructureHighlights: "Improving road connectivity in a hilly region, promoting tourism.",
        demographics: "Diverse population with various languages.",
        policies: "Emphasis on sustainable tourism, agriculture, and skill development.",
    },
    {
        id: "jharkhand",
        name: "Jharkhand",
        type: "state",
        cardImage: jharkhand,
        gallery: [jharkhand],
        keyIndustries: ["Mining", "Manufacturing"],
        investmentOpportunities: "Mining and mineral-based industries",
        majorCities: ["Ranchi", "Jamshedpur"],
        economicAchievements: "Economic growth driven by mining and mineral resources.",
        infrastructureHighlights: "Improving road and rail connectivity in a resource-rich region.",
        demographics: "Tribal and non-tribal populations with a variety of languages.",
        policies: "Policies to promote mining, industry, and inclusive growth.",
    },
    {
        id: "west-bengal",
        name: "West Bengal",
        type: "state",
        cardImage: westbengal,
        gallery: [westbengal],
        keyIndustries: ["Agriculture", "Manufacturing", "Services"],
        investmentOpportunities: "Ports, manufacturing and services",
        majorCities: ["Kolkata", "Howrah"],
        economicAchievements: "Diverse economy with a focus on agriculture, manufacturing, and services.",
        infrastructureHighlights: "Well-developed transportation networks, ports, and educational institutions.",
        demographics: "Highly populous with Bengali as the primary language.",
        policies: "Emphasis on industrial growth, agriculture, and education.",
    },
    {
        id: "karnataka",
        name: "Karnataka",
        type: "state",
        cardImage: karnataka,
        gallery: [karnataka],
        keyIndustries: ["IT", "Manufacturing", "Agriculture"],
        investmentOpportunities: "IT and tech manufacturing",
        majorCities: ["Bengaluru", "Mysore"],
        economicAchievements: "Strong economy with a focus on IT, manufacturing, and agriculture.",
        infrastructureHighlights: "Well-developed road networks, IT hubs, and educational institutions.",
        demographics: "Diverse population with Kannada as the primary language.",
        policies: "Pro-business policies, focus on IT and innovation, and sustainable development.",
    },
    {
        id: "andaman-and-nicobar",
        name: "Andaman and Nicobar",
        type: "ut",
        cardImage: andamanandnicobar,
        gallery: [andamanandnicobar],
        keyIndustries: ["Tourism", "Fisheries"],
        investmentOpportunities: "Eco-tourism and fisheries",
        majorCities: ["Port Blair"],
        economicAchievements: "Developing tourism and fisheries sectors.",
        infrastructureHighlights: "Improving connectivity, eco-tourism, and sustainable resource management.",
        demographics: "Diverse population with multiple languages spoken.",
        policies: "Focus on promoting tourism, environmental conservation, and fisheries.",
    },
    {
        id: "kerala",
        name: "Kerala",
        type: "state",
        cardImage: kerala,
        gallery: [kerala],
        keyIndustries: ["Tourism", "Services"],
        investmentOpportunities: "Healthcare, tourism and services",
        majorCities: ["Thiruvananthapuram", "Kochi"],
        economicAchievements: "High human development indicators, driven by tourism, remittances, and services.",
        infrastructureHighlights: "Quality healthcare, education, and modern transportation.",
        demographics: "Literate and diverse population with Malayalam as the primary language.",
        policies: "Emphasis on social welfare, healthcare, and education.",
    },
    {
        id: "chandigarh",
        name: "Chandigarh",
        type: "ut",
        cardImage: chandigarh,
        gallery: [chandigarh],
        keyIndustries: ["Services", "Education"],
        investmentOpportunities: "Education and services",
        majorCities: ["Chandigarh"],
        economicAchievements: "A prosperous city with a diverse economy, including government services and education.",
        infrastructureHighlights: "Well-planned city with modern infrastructure and educational institutions.",
        demographics: "Diverse population, primarily Hindi and Punjabi speakers.",
        policies: "Focus on urban development, education, and healthcare.",
    },
    {
        id: "maharashtra",
        name: "Maharashtra",
        type: "state",
        cardImage: maharashtra,
        gallery: [maharashtra],
        keyIndustries: ["Finance", "Industry", "Agriculture"],
        investmentOpportunities: "Finance, industry and infrastructure",
        majorCities: ["Mumbai", "Pune"],
        economicAchievements: "Economic powerhouse with a diverse economy, including finance, industry, and agriculture.",
        infrastructureHighlights: "Well-developed transport, industrial hubs, and educational institutions.",
        demographics: "Diverse population with Marathi as the primary language.",
        policies: "Business-friendly policies, focus on industrialization, and infrastructure development.",
    },
    {
        id: "dadra-and-nagar-haveli",
        name: "Dadra & Nagar Haveli",
        type: "ut",
        cardImage: dadraandnagarhaveli,
        gallery: [dadraandnagarhaveli],
        keyIndustries: ["Small-scale Industry"],
        investmentOpportunities: "Local industry development",
        majorCities: ["Silvassa"],
        economicAchievements: "Developing agriculture and small-scale industries.",
        infrastructureHighlights: "Improving road networks and promoting local industries.",
        demographics: "Diverse population with various languages.",
        policies: "Emphasis on local industry development and welfare.",
    },
    {
        id: "madhya-pradesh",
        name: "Madhya Pradesh",
        type: "state",
        cardImage: madhyapradesh,
        gallery: [madhyapradesh],
        keyIndustries: ["Agriculture", "Manufacturing"],
        investmentOpportunities: "Agri-processing and industry",
        majorCities: ["Bhopal", "Indore"],
        economicAchievements: "Gradual economic growth with an emphasis on agriculture and manufacturing.",
        infrastructureHighlights: "Expanding road and rail networks, improving connectivity.",
        demographics: "Diverse population with a predominantly Hindi-speaking population.",
        policies: "Initiatives to promote industries and skill development.",
    },
    {
        id: "daman-and-diu",
        name: "Daman & Diu",
        type: "ut",
        cardImage: damananddiu,
        gallery: [damananddiu],
        keyIndustries: ["Tourism", "Small Industry"],
        investmentOpportunities: "Tourism and small-scale industry",
        majorCities: ["Daman"],
        economicAchievements: "Focus on tourism and small-scale industries.",
        infrastructureHighlights: "Improving transportation and tourism infrastructure.",
        demographics: "Diverse population with various languages.",
        policies: "Promoting tourism and small-scale industries.",
    },
    {
        id: "manipur",
        name: "Manipur",
        type: "state",
        cardImage: manipur,
        gallery: [manipur],
        keyIndustries: ["Agriculture", "Handicrafts"],
        investmentOpportunities: "Handicrafts and agri-value chains",
        majorCities: ["Imphal"],
        economicAchievements: "Developing its economy with a focus on agriculture and handicrafts.",
        infrastructureHighlights: "Improving road connectivity in a hilly region.",
        demographics: "Diverse tribal population with Meiteilon as the primary language.",
        policies: "Focus on preserving indigenous culture and promoting cottage industries.",
    },
    {
        id: "jammu-and-kashmir",
        name: "Jammu & Kashmir",
        type: "ut",
        cardImage: jammuandkashmir,
        gallery: [jammuandkashmir],
        keyIndustries: ["Agriculture", "Tourism", "Handicrafts"],
        investmentOpportunities: "Tourism and horticulture",
        majorCities: ["Srinagar", "Jammu"],
        economicAchievements: "Transitioning economy with agriculture, horticulture, and handicrafts.",
        infrastructureHighlights: "Developing connectivity and tourism infrastructure.",
        demographics: "Diverse population with multiple languages, including Urdu, Dogri, and Kashmiri.",
        policies: "Emphasis on tourism, agriculture, and inclusive development.",
    },
    {
        id: "meghalaya",
        name: "Meghalaya",
        type: "state",
        cardImage: meghalaya,
        gallery: [meghalaya],
        keyIndustries: ["Agriculture", "Tourism", "Minerals"],
        investmentOpportunities: "Eco-tourism and mineral value chains",
        majorCities: ["Shillong"],
        economicAchievements: "Agriculture, tourism, and mineral resources contribute to the economy.",
        infrastructureHighlights: "Developing transportation and tourism infrastructure.",
        demographics: "Diverse tribal population with Khasi and Garo as prominent languages.",
        policies: "Emphasis on sustainable tourism and preserving tribal heritage.",
    },
    {
        id: "lakshadweep",
        name: "Lakshadweep",
        type: "ut",
        cardImage: lakshadweep,
        gallery: [lakshadweep],
        keyIndustries: ["Fisheries", "Tourism"],
        investmentOpportunities: "Fisheries and eco-tourism",
        majorCities: ["Kavaratti"],
        economicAchievements: "Economic growth through fisheries and tourism.",
        infrastructureHighlights: "Improving transportation networks and eco-tourism.",
        demographics: "Predominantly Muslim population with Malayalam as the primary language.",
        policies: "Focus on sustainable fishing, tourism, and environmental conservation.",
    },
    {
        id: "mizoram",
        name: "Mizoram",
        type: "state",
        cardImage: mizoram,
        gallery: [mizoram],
        keyIndustries: ["Agriculture", "Handicrafts"],
        investmentOpportunities: "Handicrafts and niche agriculture",
        majorCities: ["Aizawl"],
        economicAchievements: "Gradual economic growth with a focus on agriculture and handicrafts.",
        infrastructureHighlights: "Improving road connectivity in a hilly region.",
        demographics: "Diverse tribal population with Mizo as the primary language.",
        policies: "Focus on preserving indigenous culture and promoting cottage industries.",
    },
    {
        id: "puducherry",
        name: "Puducherry",
        type: "ut",
        cardImage: puducherry,
        gallery: [puducherry],
        keyIndustries: ["Tourism", "Services"],
        investmentOpportunities: "Tourism and services",
        majorCities: ["Puducherry"],
        economicAchievements: "Growing economy with tourism, agriculture, and services sectors.",
        infrastructureHighlights: "Well-developed transportation and healthcare facilities.",
        demographics: "Diverse population with multiple languages spoken.",
        policies: "Emphasis on tourism, education, and healthcare.",
    },
]

export default statesData